### ISSUE TITLE
Hyperlink is Wrong

### ISSUE THREAD

**Issue by arindammajee** [ieee-ju/ieee-ju.github.io#12]
The hyperlink in the line no 278 of team1.html file is wrong. Please correct it. It is not not redirecting to the profile of Ganseh Shaw. Instead of it is redirecting to facebook.com/profile.php 

Here is he link of that line in which the hyperlink is wrong.

https://github.com/ieee-ju/ieee-ju.github.io/blob/master/team1.html#L278

**Comment by biparnakroy** [comment]
Thankyou @Arindam-coder , for pointing this out. We will fix it very soon!!
