### ISSUE TITLE
Adding Go to the website button in the events section.

### ISSUE THREAD

**Issue by iamtamodip** [ieee-ju/ieee-ju.github.io#26]
People should know there exist separate pages for each of the events at a first glance.

**Comment by biparnakroy** [comment]
ICU

**Comment by iamtamodip** [comment]
4 PBA

**Comment by biparnakroy** [comment]
@aspiringstar @shreyab1111 can any one of you look into this.

**Comment by aspiringstar** [comment]
Okay. Looking into it.
