### ISSUE TITLE
Remove Pre-loader

### ISSUE THREAD

**Issue by ayan-biswas0412** [ieee-ju/ieee-ju.github.io#31]
https://github.com/ieee-ju/ieee-ju.github.io/blob/d231bd9143e49175ae9dd6bb4d637587e07f1d8f/index.html#L1310
If anybody is free, please comment out this and make a PR 
Check for contact pages also, please comment out that from there also
@ieee-ju/tech-team-core please see this and fix this if anyone is available

**Comment by p3jitnath** [comment]
Done.

**Comment by ayan-biswas0412** [comment]
nice work 

![200](https://user-images.githubusercontent.com/52851184/122805880-46adb680-d2e7-11eb-8885-a8cde1e8eda8.gif)
